---

# Install
- include: install.yml
  tags:
    - manala_docker

# Services
- include: services.yml
  tags:
    - manala_docker
    - manala_docker.services
    - manala.services

# Applications
- include: applications.yml
  tags:
    - manala_docker
